### ISSUE TITLE
Abc rejection looks to be slow

### ISSUE THREAD

**Issue by marcjwilliams1** [marcjwilliams1/ApproxBayes.jl#12]
Lots of time spent in getproposal function?

**Comment by ChrisRackauckas** [comment]
It's because you're using an array of distributions. That's not type-stable. If you instead made the priors a tuple of distributions then it would have the right type information.

However, you have to go a little further than that as well. Since `p.distributions[i]` will be iterating over different types, the `getindex` function is still not type-stable. The way to handle this is thus to write it as an inlining set of recursive calls:

```julia
update_newparams!(newparams,p::Prior) = update_newparams!(newparams,1,p.distributions...)
@inline function update_newparams!(newparams,i,x,y...)
  newparams[i] = rand(x)
  update_newparams!(newparams,i,y...)
end
@inline function update_newparams!(newparams,i,x)
  newparams[i] = rand(x)
end
```

should be it. That's thus infer everything when the number of prior distributions is `<16`, and then do indefinitely more after https://github.com/JuliaLang/julia/pull/23912 (so the limit is already fixed in v0.7)

**Comment by marcjwilliams1** [comment]
@ChrisRackauckas great, thanks for the tip and the nice proposed solution

**Comment by marcjwilliams1** [comment]
Needed to add i+1 to the above code to implement the recursion

So code is:
```julia
update_newparams!(newparams,p::Prior) = update_newparams!(newparams, 1, p.distribution...)

@inline function update_newparams!(newparams, i, x, y...)
  newparams[i] = rand(x)
  update_newparams!(newparams, i + 1, y...)
end
@inline function update_newparams!(newparams,i,x)
  newparams[i] = rand(x)
end
```

**Comment by marcjwilliams1** [comment]
this results in about a 10-20% speed up

**Comment by marcjwilliams1** [comment]
should do something similar for calculating prior prob. `priorprob` function in util.jl
